### ISSUE TITLE
Some file names and parameter names described in the README do not match actual

### ISSUE THREAD

**Issue by soudegesu** [aws-samples/amazon-cloudfront-continuous-deployment#1]
Some file names and parameter names described in the README do not match actual. 

It's as follows

- File names
  - `pipeline-input-variable.ts` to `pipeline-input-variables.ts`
  - `cf-distribution.config.ts` to `cf-distribution-config.ts`
- Parameter
  - `PIPELINE_CODE_REPO_NAME` to `PIPELINE_CODE_REPO`

**Comment by graviavu** [comment]
Thanks for submitting the issue. We will review the issue and the corresponding PR and respond soon.

**Comment by graviavu** [comment]
PR merged.
