### ISSUE TITLE
CodePipeline step StagingDistribution-Change Deploy Failed (Post Promotion)

### ISSUE THREAD

**Issue by jp-904** [aws-samples/amazon-cloudfront-continuous-deployment#8]
Failed CodePipeline step `StagingDistribution-Change` as following after push code change to CodeCommit
![image](https://github.com/aws-samples/amazon-cloudfront-continuous-deployment/assets/44284690/b45409a1-4e8a-49c9-bec7-0f40f4890b65)

The Error message in CodePipeline `Action Execution Details` - 

`First failed resource reason
Resource handler returned message: "Invalid request provided: One or more fields updated are not supported for continuous deployment. (Service: CloudFront, Status Code: 400)"`

Cloudformation error message - 

`Resource handler returned message: "Invalid request provided: One or more fields updated are not supported for continuous deployment. (Service: CloudFront, Status Code: 400, Request ID: 5131da37-6a8e-42f7-a901-a42777c0c902)" (RequestToken: 8d9a0c18-9fe6-f927-e6eb-7889521fa47c, HandlerErrorCode: InvalidRequest)`

![image](https://github.com/aws-samples/amazon-cloudfront-continuous-deployment/assets/44284690/0fefe877-cb6d-4c83-82e2-046082bd4247)

This happened after pushed new CDN configuration change after promote Staging Distribution. None of the CDN config is allowed to be updated

**Comment by graviavu** [comment]
Please confirm the configuration change you are trying to make is listed in documentation for [configuration allowed for continuous deployment](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/continuous-deployment.html#updating-staging-and-primary-distributions).

**Comment by jp-904** [comment]
Thanks Graviavu, yes, the update I tested under the listed. 
Tried updated: 

- Existing origin
- New origin
- Default root object
- Description (comment)

None of them is allowed and getting the same error

**Comment by jp-904** [comment]
Thanks. I just re-test by updating `defaultRootObject` and failed. Could you share how you test ?
Here is the code commit change - 

![image](https://github.com/aws-samples/amazon-cloudfront-continuous-deployment/assets/44284690/cb31c6ee-3fc2-4ab7-8bb2-7e9b3655bd83)


Cloud Trail logs - 

![image](https://github.com/aws-samples/amazon-cloudfront-continuous-deployment/assets/44284690/87e266f1-9125-446c-8281-bc1027326e6d)
![image](https://github.com/aws-samples/amazon-cloudfront-continuous-deployment/assets/44284690/85161bc6-cd09-43d3-981e-1da53c5d2aaf)

**Comment by graviavu** [comment]
I follow the steps under this section of [readme instructions
](https://github.com/aws-samples/amazon-cloudfront-continuous-deployment#step---c-change-distribution-configuration-and-deploy). With additional step to make changes to distribution configuration.

I validated the configuration based on the CloudTrail logs and payload looks exactly same as my test. Is it possible to make the change to staging distribution from console and validate if that works and compare the CloudTrail log payload?

**Comment by jp-904** [comment]
Thank you Graviavu. It turns out that `webAclId` is missing from cd-distribution-config. When it first created the Primary stack, the webAclId was generated automatically even it is not defined. Somehow when it created the staging distribution, the webAclId became empty which is required for the subsequent config update.
